### ISSUE TITLE
Add more units.

### ISSUE THREAD

**Issue by Ayfri** [mudlabs/short-scale-units#3]
Hi!
I'm making an incremental game in JS, (a tycoon game, where you will have, not in much time, pretty big numbers.
(For example in Adventure Capitalist, you can get like `Quadragintillion` in a few days, and `Ducentillion` in a few weeks.)
And I need to be able to display reeaaaally big numbers for my game, can you add a bunch?

**Comment by mudlabs** [comment]
Please update to v1.1.2

**Comment by Ayfri** [comment]
Thank you a lot!
