### ISSUE TITLE
Let methods be used with strings.

### ISSUE THREAD

**Issue by Ayfri** [mudlabs/short-scale-units#5]
Hi, I'm using [this library](https://www.npmjs.com/package/bigfloat.js) that uses strings for numbers so you can have really long numbers (basically infinite), but I can't use your library as such. You could also export units so I just recode yours using the units :)

(Also you should accept BigInts :))

**Comment by mudlabs** [comment]
H1 @Ayfri, you can pass numbers as stings. So If you are using BigInt all you have to do is convert it to a String first.

```js
const ssu = require("short-scale-units");
const big = BigInt(1284518732469826598347598347569348750275984567983467593486598734659834798347984357693146759734816598347598341765943817659847659843765934876594387593487659843765984375984375983475943879438759834759843759843759834798437598341759831475984317);

ssu.unitNameFromNumber(String(big)); // "octoseptuagintillion"
```

I don't follow what you mean here _("You could also export units so I just recode yours using the units")_.

**Comment by mudlabs** [comment]
@Ayfri how are we going here; Is this issue closed?

**Comment by Ayfri** [comment]
Hey, nice for the update, I'm busy right now until Sunday so I'll try that day!

**Comment by Ayfri** [comment]
Hey, I've found time to test this (I was really busy at a moment, then worked on another feature than that on my repo etc).
![image](https://user-images.githubusercontent.com/34159136/115420710-a7dbdf80-a1fb-11eb-970d-8c1547815fa4.png)
Actually, it still says that the methods are waiting for numbers.

I'm using the `1.1.2` version.
_(also you should provide releases in this repo with changelogs :))_

**Comment by mudlabs** [comment]
I see, so the code works but you have a type casting issue.

What do think about exporting a `ShortScaleUnit` _type_ to handle this?

```ts
export type ShortScaleUnit = number | bigint | string;
```

Then I'll rewrite the API to specify this type, for example;
```ts
export function getUnitPower(number: ShortScaleUnit): number;
```

<br/>

---


So your code above would become,
```ts
//...
export function showWithFullExtension(number: number | BigFloat): string {
    return SSU.getUnitPower(number) + SSU.unitNameFromNumber(number);
}
```

The package will workout if it was handed a `number`, `bigint` or `string` internally with a simple `typeof` check and make the necessary conversion.

**Comment by Ayfri** [comment]
That would be really clever !

**Comment by mudlabs** [comment]
Ok, try updating to `v1.2.0`.

You should be able to pass in you _numbers_ / _bigints_ with no issue.

**Comment by Ayfri** [comment]
Nice it works!
